/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as LibrarySubscriptionsRouteImport } from './routes/library.subscriptions'
import { Route as LibraryPlaylistsRouteImport } from './routes/library.playlists'
import { Route as LibraryLikedRouteImport } from './routes/library.liked'
import { Route as ChannelChannelNameRouteImport } from './routes/channel.$channelName'
import { Route as PlaylistChannelSlugRouteImport } from './routes/playlist.$channel.$slug'
import { Route as LibraryPlaylistsPlaylistIdRouteImport } from './routes/library.playlists.$playlistId'
import { Route as ApiPublicSyncVideosRouteImport } from './routes/api/public/sync-videos'
import { Route as ApiPublicSyncR2RouteImport } from './routes/api/public/sync-r2'
import { Route as ApiPublicFeedRouteImport } from './routes/api/public/feed'
import { Route as ApiPublicAuthConfigRouteImport } from './routes/api/public/auth-config'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySubscriptionsRoute = LibrarySubscriptionsRouteImport.update({
  id: '/library/subscriptions',
  path: '/library/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsRoute = LibraryPlaylistsRouteImport.update({
  id: '/library/playlists',
  path: '/library/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLikedRoute = LibraryLikedRouteImport.update({
  id: '/library/liked',
  path: '/library/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelNameRoute = ChannelChannelNameRouteImport.update({
  id: '/channel/$channelName',
  path: '/channel/$channelName',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistChannelSlugRoute = PlaylistChannelSlugRouteImport.update({
  id: '/playlist/$channel/$slug',
  path: '/playlist/$channel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPlaylistsPlaylistIdRoute =
  LibraryPlaylistsPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => LibraryPlaylistsRoute,
  } as any)
const ApiPublicSyncVideosRoute = ApiPublicSyncVideosRouteImport.update({
  id: '/api/public/sync-videos',
  path: '/api/public/sync-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncR2Route = ApiPublicSyncR2RouteImport.update({
  id: '/api/public/sync-r2',
  path: '/api/public/sync-r2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedRoute = ApiPublicFeedRouteImport.update({
  id: '/api/public/feed',
  path: '/api/public/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthConfigRoute = ApiPublicAuthConfigRouteImport.update({
  id: '/api/public/auth-config',
  path: '/api/public/auth-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/channel/$channelName': typeof ChannelChannelNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/playlists': typeof LibraryPlaylistsRouteWithChildren
  '/library/subscriptions': typeof LibrarySubscriptionsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/sync-r2': typeof ApiPublicSyncR2Route
  '/api/public/sync-videos': typeof ApiPublicSyncVideosRoute
  '/library/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/playlist/$channel/$slug': typeof PlaylistChannelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/channel/$channelName': typeof ChannelChannelNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/playlists': typeof LibraryPlaylistsRouteWithChildren
  '/library/subscriptions': typeof LibrarySubscriptionsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/sync-r2': typeof ApiPublicSyncR2Route
  '/api/public/sync-videos': typeof ApiPublicSyncVideosRoute
  '/library/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/playlist/$channel/$slug': typeof PlaylistChannelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/channel/$channelName': typeof ChannelChannelNameRoute
  '/library/liked': typeof LibraryLikedRoute
  '/library/playlists': typeof LibraryPlaylistsRouteWithChildren
  '/library/subscriptions': typeof LibrarySubscriptionsRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/api/public/auth-config': typeof ApiPublicAuthConfigRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/api/public/sync-r2': typeof ApiPublicSyncR2Route
  '/api/public/sync-videos': typeof ApiPublicSyncVideosRoute
  '/library/playlists/$playlistId': typeof LibraryPlaylistsPlaylistIdRoute
  '/playlist/$channel/$slug': typeof PlaylistChannelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/jobs'
    | '/sitemap.xml'
    | '/channel/$channelName'
    | '/library/liked'
    | '/library/playlists'
    | '/library/subscriptions'
    | '/watch/$videoId'
    | '/api/public/auth-config'
    | '/api/public/feed'
    | '/api/public/sync-r2'
    | '/api/public/sync-videos'
    | '/library/playlists/$playlistId'
    | '/playlist/$channel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/jobs'
    | '/sitemap.xml'
    | '/channel/$channelName'
    | '/library/liked'
    | '/library/playlists'
    | '/library/subscriptions'
    | '/watch/$videoId'
    | '/api/public/auth-config'
    | '/api/public/feed'
    | '/api/public/sync-r2'
    | '/api/public/sync-videos'
    | '/library/playlists/$playlistId'
    | '/playlist/$channel/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/jobs'
    | '/sitemap.xml'
    | '/channel/$channelName'
    | '/library/liked'
    | '/library/playlists'
    | '/library/subscriptions'
    | '/watch/$videoId'
    | '/api/public/auth-config'
    | '/api/public/feed'
    | '/api/public/sync-r2'
    | '/api/public/sync-videos'
    | '/library/playlists/$playlistId'
    | '/playlist/$channel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  JobsRoute: typeof JobsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChannelChannelNameRoute: typeof ChannelChannelNameRoute
  LibraryLikedRoute: typeof LibraryLikedRoute
  LibraryPlaylistsRoute: typeof LibraryPlaylistsRouteWithChildren
  LibrarySubscriptionsRoute: typeof LibrarySubscriptionsRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
  ApiPublicAuthConfigRoute: typeof ApiPublicAuthConfigRoute
  ApiPublicFeedRoute: typeof ApiPublicFeedRoute
  ApiPublicSyncR2Route: typeof ApiPublicSyncR2Route
  ApiPublicSyncVideosRoute: typeof ApiPublicSyncVideosRoute
  PlaylistChannelSlugRoute: typeof PlaylistChannelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/subscriptions': {
      id: '/library/subscriptions'
      path: '/library/subscriptions'
      fullPath: '/library/subscriptions'
      preLoaderRoute: typeof LibrarySubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/playlists': {
      id: '/library/playlists'
      path: '/library/playlists'
      fullPath: '/library/playlists'
      preLoaderRoute: typeof LibraryPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/liked': {
      id: '/library/liked'
      path: '/library/liked'
      fullPath: '/library/liked'
      preLoaderRoute: typeof LibraryLikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelName': {
      id: '/channel/$channelName'
      path: '/channel/$channelName'
      fullPath: '/channel/$channelName'
      preLoaderRoute: typeof ChannelChannelNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$channel/$slug': {
      id: '/playlist/$channel/$slug'
      path: '/playlist/$channel/$slug'
      fullPath: '/playlist/$channel/$slug'
      preLoaderRoute: typeof PlaylistChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/playlists/$playlistId': {
      id: '/library/playlists/$playlistId'
      path: '/$playlistId'
      fullPath: '/library/playlists/$playlistId'
      preLoaderRoute: typeof LibraryPlaylistsPlaylistIdRouteImport
      parentRoute: typeof LibraryPlaylistsRoute
    }
    '/api/public/sync-videos': {
      id: '/api/public/sync-videos'
      path: '/api/public/sync-videos'
      fullPath: '/api/public/sync-videos'
      preLoaderRoute: typeof ApiPublicSyncVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-r2': {
      id: '/api/public/sync-r2'
      path: '/api/public/sync-r2'
      fullPath: '/api/public/sync-r2'
      preLoaderRoute: typeof ApiPublicSyncR2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed': {
      id: '/api/public/feed'
      path: '/api/public/feed'
      fullPath: '/api/public/feed'
      preLoaderRoute: typeof ApiPublicFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-config': {
      id: '/api/public/auth-config'
      path: '/api/public/auth-config'
      fullPath: '/api/public/auth-config'
      preLoaderRoute: typeof ApiPublicAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryPlaylistsRouteChildren {
  LibraryPlaylistsPlaylistIdRoute: typeof LibraryPlaylistsPlaylistIdRoute
}

const LibraryPlaylistsRouteChildren: LibraryPlaylistsRouteChildren = {
  LibraryPlaylistsPlaylistIdRoute: LibraryPlaylistsPlaylistIdRoute,
}

const LibraryPlaylistsRouteWithChildren =
  LibraryPlaylistsRoute._addFileChildren(LibraryPlaylistsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  JobsRoute: JobsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChannelChannelNameRoute: ChannelChannelNameRoute,
  LibraryLikedRoute: LibraryLikedRoute,
  LibraryPlaylistsRoute: LibraryPlaylistsRouteWithChildren,
  LibrarySubscriptionsRoute: LibrarySubscriptionsRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
  ApiPublicAuthConfigRoute: ApiPublicAuthConfigRoute,
  ApiPublicFeedRoute: ApiPublicFeedRoute,
  ApiPublicSyncR2Route: ApiPublicSyncR2Route,
  ApiPublicSyncVideosRoute: ApiPublicSyncVideosRoute,
  PlaylistChannelSlugRoute: PlaylistChannelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
